[tox]
envlist = py39, py310, py311, py312
isolated_build = true

[testenv]
description = Run test suite
deps =
    pytest
    pytest-xdist
    pytest-timeout
    aiohttp
    urllib3

commands =
    pytest {posargs}

setenv =
    PYTHONUNBUFFERED=1

passenv =
    CI

[testenv:lint]
description = run flake8
skip_install = true
deps = 
    flake8
commands = 
    flake8 walleta


[testenv:mypy]
description = run mypy
deps = 
    mypy
commands = 
    mypy --strict walleta {posargs}
